### ISSUE TITLE
page mailing list

### ISSUE THREAD

**Issue by florianroulet** [ToursJUG/site#10]
le contenu de l'iframe est bof.
l'iframe rajoute des cookie sendinblue et google, donc nécessite un bandeau RGPD.
Est-ce qu'on vire pour un lien mailto ? @ptitbob

**Comment by ptitbob** [comment]
Oui, mais cela se passe dans le repo du thème ;)

**Comment by ptitbob** [comment]
transféré sur le repo du theme :)
